### ISSUE TITLE
Release Please

### ISSUE THREAD

**Issue by jensens** [collective/collective.plonetruegallery#47]
at collective/collective.github.com#879 the request for a release was placed, I move over here.

**Comment by jensens** [comment]
cc @vangheem @witsch @frisi et al

**Comment by frisi** [comment]
thanks @jensens
i did not work on this package for years.  @bsuttor as you are the package owner on pypi i ask you if you can do a new release as requested by @sandrarum

**Comment by bsuttor** [comment]
Hello,
I just check PR (https://github.com/collective/collective.plonetruegallery/pull/46) but it seems changelog is missing.
I will update it and make a new release.

@sandrarum thank you for the PR ;-)
