### ISSUE TITLE
Update Plone versions and README

### ISSUE THREAD

**Issue by svx** [collective/collective.plonetruegallery#50]
According to: https://github.com/collective/collective.plonetruegallery/blob/master/docs/HISTORY.txt

This add-on works now with Plone 5, if so the README should be updated, telling this and if needed upgrade instructions

**Comment by tkimnguyen** [comment]
Also needs clearer instructions on how to use (e.g. step by step, screen shots)

**Comment by lingxiaoyang** [comment]
+1

**Comment by tkimnguyen** [comment]
Added Plone 5.0 pypi classifier in https://github.com/collective/collective.plonetruegallery/commit/f4b3f38e0aa71715416a698407fc20c1b5ef21e0

**Comment by tkimnguyen** [comment]
Mentioned Plone 5 compatibility in https://github.com/collective/collective.plonetruegallery/commit/259bf7c119c238f3c496f4bbb57df8e60c1043c9

**Comment by tkimnguyen** [comment]
Added screenshots and clarified instructions, in https://github.com/collective/collective.plonetruegallery/commit/2a1b66d38f6395a3c37cb47ee5940c3f4d46bd7c

**Comment by tkimnguyen** [comment]
...and released to https://pypi.python.org/pypi/collective.plonetruegallery

**Comment by lingxiaoyang** [comment]
Thank you!
